### ISSUE TITLE
我运行test.py的时候报错no labels found in  ...../test, 测试集也要txt标注文件吗？

### ISSUE THREAD

**Issue by minuet-red** [KevinMuyaoGuo/yolov5s_for_satellite_imagery#5]
![image](https://user-images.githubusercontent.com/78399534/107740622-8b787e00-6d46-11eb-82d4-5f1da08fe988.png)
请问测试集也需要split分块操作和text标注文件吗？

**Comment by AaroAaron** [comment]
为什么我在运行train.py的时候就出现了这样的错误？我也有相应的标注文件呀。。。
